---

- name: Copy redis exporter script
  ansible.builtin.template:
    src: "redis_exporter"
    dest: /usr/local/bin/redis_exporter
    mode: 0755
    owner: root
    group: root

- name: Copy redis exporter script
  ansible.builtin.template:
    src: "redis_exporter.service"
    dest: /etc/systemd/system/redis_exporter.service
    mode: 0644
    owner: root
    group: root

- name: Restart redis exporter service is restarted
  ansible.builtin.service:
    name: Redis_exporter
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for redis exporter to become ready
  ansible.builtin.wait_for:
    host: "{{ redis_exporter_server_bind }}"
    port: "{{ redis_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
