---
# handlers for ansible-role-docker-redis_exporter

- name: Restart redis_exporter
  ansible.builtin.service:
    name: Redis_exporter
    state: restarted
    enabled: true

- name: Start redis_exporter
  ansible.builtin.service:
    name: Redis_exporter
    state: started
    enabled: true

- name: Reload redis_exporter
  ansible.builtin.service:
    name: Redis_exporter
    state: reloaded
    enabled: true
